[project]
name = "mach3sbitools"
version = "3.3.0"
description = "Interface between SBI and MaCh3"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "torch",
    "sbi",
    "uproot",
    "matplotlib",
    "ipython",
    "ipykernel",
    "ipywidgets",
    "click",
    "pyarrow",
    "scipy-stubs~=1.17.1",
    "arviz",
    "rich",
    "pre-commit",
    "pymc",
    "types-PyYAML",
    "click-option-group",
    "pytest",
    "pytest-cov",
    "ruff",
    "mypy",
    "sphinx",
    "importlib-metadata",
    "lightning",
    "awkward[numba]",
    "corner"
]

[project.optional-dependencies]
docs = [
    "sphinx",
    "sphinx-click==4.4.0", # OLD VERSION NEEDED
    "sphinx-autodoc-typehints>=2.3.0",
    "sphinxcontrib-bibtex",
    "furo"
]

[project.scripts]
mach3sbi = "mach3sbitools.apps.main_cli:cli"

[tool.pytest.ini_options]
addopts = "-v --tb=short --cov=mach3sbitools tests/  --cov-report=term-missing"
markers = [
    "slow: mark a test that takes a long time to run.",
    "mach3tutorial: mark a test that requires MaCh3Tutorial",
]
# We really don't need these in testing as it complains
# about the tiny test models!
filterwarnings = [
    "ignore::UserWarning:lightning.*",
]

[tool.coverage.run]
source = ["mach3sbitools"]
# We also ignore examples here, there will be a few tests but there's no point doing
# a full integration test!
omit = ["tests/*", "scripts/*", "tutorial/*", "src/mach3sbitools/examples/*"]

# * See https://docs.astral.sh/ruff/rules/ for details on Ruff's linting options
[tool.ruff.lint]
select = [
    "E",    # pycodestyle errors
    "F",    # check for errors using PyFlakes
    "I",    # best practices for import calls
    "UP",   # suggestions for code modernization
    "RUF",  # build in Ruff warnings
    "R",    # refactoring suggestions
]
ignore = [
    "E501", # Don't enforce line lengths within a linting context
]
allowed-confusables = ["σ", "α"] # We need sigmas

[tool.mypy]
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true
exclude = ["build"]
